INSERT INTO Genre (name) VALUES ('Baaaad');
INSERT INTO Genre (name) VALUES ('Baaaad1');
INSERT INTO Genre (name) VALUES ('Baaaad2');
INSERT INTO Genre (name) VALUES ('Baaaad3');
INSERT INTO Genre (name) VALUES ('Baaaad4');
INSERT INTO Genre (name) VALUES ('Baaaad5');
INSERT INTO Genre (name) VALUES ('Baaaad6');
INSERT INTO Genre (name) VALUES ('Baaaad7');
INSERT INTO Genre (name) VALUES ('Baaaad8');
INSERT INTO Author (fio) VALUES ('Pushkin');
INSERT INTO Author (fio) VALUES ('Lermontov');
INSERT INTO Author (fio) VALUES ('Tolstoy');
INSERT INTO Author (fio) VALUES ('Dostoevsky');
INSERT INTO Book (name, authorId, genreId, pagecount, description) VALUES ('Kniga1', 1, 2, 345, 'flkgdflkn');
INSERT INTO Book (name, authorId, genreId, pagecount, description) VALUES ('Kniga2', 2, 2, 345, 'ssss');
INSERT INTO Book (name, authorId, genreId, pagecount, description) VALUES ('Kniga3', 3, 2, 345, 'rrrr');
INSERT INTO Book (name, authorId, genreId, pagecount, description) VALUES ('Kniga4', 3, 1, 345, 'eeeee');
INSERT INTO Book (name, authorId, genreId, pagecount, description) VALUES ('Kniga5', 1, 3, 345, 'bbbbb');
INSERT INTO Book (name, authorId, genreId, pagecount, description) VALUES ('Kniga6', 4, 4, 345, 'qqwwqwq');